language: php
php:
  - 5.6
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly
script:
  - composer install --prefer-dist --no-interaction
  - mkdir -p build/logs
  - vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls
